# !! File must end with empty line !!
dependencies:
  # !! "alias: preview" must be last entry in dependencies array !!
  # !! Place custom dependencies above !!
- name: mood-feed-backend
  version: 1.0.5
  repository: http://chartmuseum-jx.35.224.13.149.nip.io
- name: mysql
  version: 1.6.6
  repository: https://kubernetes-charts.storage.googleapis.com

- alias: preview
  name: mood-feed-frontend
  repository: file://../mood-feed-frontend
