environments:
  default:
    values:
      - jx-values.yaml
repositories:
  - name: stable
    url: https://charts.helm.sh/stable
  - name: dev
    url: '{{ jxRequirements.cluster.chartRepository}}'
releases:
- chart: dev/mood-feed-backend
  name: mood-feed-backend
  wait: true
  namespace: '{{ requiredEnv "PREVIEW_NAMESPACE" }}'
  values:
    - backend-values.yaml
    - imagePullSecrets.yaml
- chart: stable/mysql
  version: 1.6.6
  name: mysql
  namespace: '{{ requiredEnv "PREVIEW_NAMESPACE" }}'
  values:
    - mysql-values.yaml
- chart: '../charts/{{ requiredEnv "APP_NAME" }}'
  name: preview
  wait: true
  createNamespace: true
  namespace: '{{ requiredEnv "PREVIEW_NAMESPACE" }}'
  values:
  - values.yaml.gotmpl
  - jx-values.yaml
  - imagePullSecrets.yaml
  hooks:
  - events: ["presync"]
    showlogs: true
    command: "jx"
    args:
    - secret
    - copy
    - --create-namespace
    - --selector
    - "secret.jenkins-x.io/replica-source=true"
    - --to
    - '{{ requiredEnv "PREVIEW_NAMESPACE" }}'
