releases:
- chart: '../charts/{{ requiredEnv "APP_NAME" }}'
  name: preview
  wait: true
  createNamespace: true
  namespace: '{{ requiredEnv "PREVIEW_NAMESPACE" }}'
  values:
  - values.yaml.gotmpl
  - jx-values.yaml
  hooks:
  - events: ["presync"]
    showlogs: true
    command: "jx"
    args:
    - secret
    - copy
    - --create-namespace
    - --selector
    - "secret.jenkins-x.io/replica-source=true"
    - --to
    - '{{ requiredEnv "PREVIEW_NAMESPACE" }}'
- chart: dev/mood-feed-backend
  version: 1.0.12
  name: mood-feed-backend
  namespace: '{{ requiredEnv "PREVIEW_NAMESPACE" }}'
- chart: stable/mysql
  version: 1.6.6
  name: mysql
  namespace: '{{ requiredEnv "PREVIEW_NAMESPACE" }}'
  values:
    - mysqlPassword: 123QWEasd
    - mysqlDatabase: mood_feed
    - mysqlUser: moodfeed
    - mysqlRootPassword: 123QWEasd
    - initializationFiles:
        mood_feed_db.sql: |-
          CREATE DATABASE IF NOT EXISTS mood_feed DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;
