apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: jx-pullrequest
  labels:
    jenkins.io/pipelineType: build
    owner: vitech-team
spec:
  pipelineRef:
    name: secrets-scanner-pipeline
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 250Mi
  serviceAccountName: tekton-build-bot
  timeout: 1h