apiVersion: tekton.dev/v1beta1
kind: PipelineRun
metadata:
  name: jx-release
  labels:
    jenkins.io/pipelineType: build
    owner: vitech-team
spec:
  pipelineRef:
    name: jx-node-release
  workspaces:
    - name: shared-data
      volumeClaimTemplate:
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
  podTemplate:
    volumes:
      - name: podinfo
        downwardAPI:
          items:
            - fieldRef:
                fieldPath: metadata.labels
              path: labels
      - name: docker-socket
        hostPath:
          path: /var/run/docker.sock
          type: Socket
  serviceAccountName: "tekton-build-bot"
  timeout: 1h
